language: python
python:
- '3.6'
- '3.7'
- 3.7-dev
install:
- pip install pyvisa
- pip install .
script:
- echo "skipping tests"
deploy:
  provider: pypi
  user: SamSchott
  skip_existing: true
  on:
    tags: true
  password:
    secure: 70aeOHoO/XgvuMW3AgikJfR9azm3q/no8qMfgoaDniMYduSpgF6c2qJor9aKRW4QSXuelNmU/814akfuptB8yi55A5P8DIsDxlttXH9JFl6bUF/O15dN+ok1oolcAXEQFmkrhuXhFMeIOaXQH8dwVqYS6DSEUG+K4X1JIfuOA3S83jHBN5H0GjXaqNvy/+kVWmYK5v1+ycNubnqcgmKcHb1BqBHVzUvZ9PGj186Bg04dghuoK94FTzuvmlMzhgwzxAbcDla6ezJmqfEwJNYOj/fPw7VQDSPiwVeksnXToXYaLMpmxgPldpw0vTdJLwJsgTuIJ2rpe5/8x1fp8e1b7sLFX/XuASqEtLTOQcbOdsioVhS7zZamhuNccY1uiZ1hkx2NBoFzGLjwwLKxxXg9uKCMflP6bm1BcRB0JQQdNmHo859tJZMsjO2zkf9XkEnMCfQ/O4x7uxDB2ar4kjWBT5KWhH/vbvAyWW2q1AHMnWWyuRoFub5sUCBEWUIpwI7fiAXhaQCl/JJpC2BdM8NGi8WqxaDcZJ9V0W+DgQeqvARfdNBh2Vcxkrm6TrnZL7Z7EeCc+Th47mfKUUxcjXxuCzopHrGrgQoR/uB8LdRQOSKnvnsltOQWLF3IbEqbVWUahttdiQFixjFf/tDzEtE4G3uSuC0fx/0xw8vxZqq2KTg=
